apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: observability
  labels:
    app.kubernetes.io/name: alloy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      serviceAccountName: alloy
      hostPID: true  # Required for pyroscope.java to access Java processes
      volumes:
        - name: config
          configMap:
            name: alloy-config
            items:
              - key: config.alloy
                path: config.alloy
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      containers:
        - name: alloy
          image: grafana/alloy:v1.8.3
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            capabilities:
              add:
                - PERFMON
                - SYS_PTRACE
                - SYS_RESOURCE
                - SYS_ADMIN
          ports:
            - name: http-metrics
              containerPort: 12345
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GRAFANA_CLOUD_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud
                  key: GRAFANA_CLOUD_USER
            - name: GRAFANA_CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud
                  key: GRAFANA_CLOUD_API_KEY
            - name: PYROSCOPE_REMOTE_WRITE
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud
                  key: PYROSCOPE_REMOTE_WRITE
            - name: PROM_REMOTE_WRITE
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud
                  key: PROM_REMOTE_WRITE
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
            initialDelaySeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /-/health
              port: 12345
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
        - name: config-reloader
          image: ghcr.io/jimmidyson/configmap-reload:v0.14.0
          args:
            - --volume-dir=/etc/alloy
            - --webhook-url=http://localhost:12345/-/reload
            - --webhook-method=POST
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
